language: elixir

otp_release:
  - 19.1
  - 20.0

elixir:
  - 1.5
  - 1.6

sudo: false

script:
  - MIX_ENV=test mix do compile --warnings-as-errors, coveralls.json

after_success:
  - bash <(curl -s https://codecov.io/bash)

