name: Elixir CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        pair:
          - otp-version: '21'
            elixir-version: '1.7'
          - otp-version: '21'
            elixir-version: '1.8'
          - otp-version: '22'
            elixir-version: '1.9'
          - otp-version: '22'
            elixir-version: '1.10'
          - otp-version: '23'
            elixir-version: '1.11'

    steps:
    - uses: actions/checkout@v2
    - name: Setup elixir
      uses: actions/setup-elixir@v1
      with:
        elixir-version: ${{ matrix.pair.elixir-version }}
        otp-version: ${{ matrix.pair.otp-version }}
    - name: Install Dependencies
      run: mix deps.get
    - name: Compile
      run: MIX_ENV=test mix do compile --warnings-as-errors
    - name: Run Tests
      run: |
        mix credo --strict
        mix test --cover
