name: Elixir CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        pair:
          - otp-version: '23'
            elixir-version: '1.12'
          - otp-version: '24'
            elixir-version: '1.13'
          - otp-version: '24'
            elixir-version: '1.14'

    steps:
    - uses: actions/checkout@v2
    - name: Setup elixir
      uses: erlef/setup-beam@v1
      with:
        elixir-version: ${{ matrix.pair.elixir-version }}
        otp-version: ${{ matrix.pair.otp-version }}
    - name: Install Dependencies
      run: mix deps.get
    - name: Compile
      run: MIX_ENV=test mix do compile --warnings-as-errors
    - name: Run Tests
      run: |
        mix credo --strict
        mix test --cover
